/*$file${.::src::state_machine.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: test-state-machine.qm
* File:  ${.::src::state_machine.c}
*
* This code has been generated by QM 5.2.1 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::src::state_machine.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"
#include "state_machine.h"
#include "bsp.h"

/* ask QM to declare the Blinky class --------------------------------------*/
/*$declare${AOs::state_machine} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::state_machine} ....................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt timeEvt;
} state_machine;

/* protected: */
static QState state_machine_initial(state_machine * const me, void const * const par);
static QState state_machine_state_1(state_machine * const me, QEvt const * const e);
static QState state_machine_state_2(state_machine * const me, QEvt const * const e);
static QState state_machine_state_3(state_machine * const me, QEvt const * const e);
/*$enddecl${AOs::state_machine} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* instantiate the Blinky active object ------------------------------------*/
static state_machine l_state_machine;

QHsm * const the_stm = (QHsm *)&l_state_machine;

/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::AO_state_machine} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::AO_state_machine} .................................................*/
QActive * const AO_state_machine = &l_state_machine.super;
/*$enddef${AOs::AO_state_machine} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* ask QM to define the Blinky class ---------------------------------------*/
/*$define${AOs::state_machine_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::state_machine_ctor} ...............................................*/
void state_machine_ctor(void) {
    state_machine *me = (state_machine *)AO_state_machine;
    QActive_ctor(&me->super, Q_STATE_CAST(&state_machine_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
/*$enddef${AOs::state_machine_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::state_machine} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::state_machine} ....................................................*/

/*${AOs::state_machine::SM} ................................................*/
static QState state_machine_initial(state_machine * const me, void const * const par) {
    /*${AOs::state_machine::SM::initial} */
    (void)par; /* unused parameter */
    /* arm the private time event to expire in 1/2s
    * and periodically every 1/2 second
    */
    QS_OBJ_DICTIONARY(&l_state_machine);
    QS_OBJ_DICTIONARY(&l_state_machine.timeEvt);

    QTimeEvt_armX(&me->timeEvt,
        BSP_TICKS_PER_SEC/2,
        BSP_TICKS_PER_SEC/2);

    QS_FUN_DICTIONARY(&state_machine_state_1);
    QS_FUN_DICTIONARY(&state_machine_state_2);
    QS_FUN_DICTIONARY(&state_machine_state_3);

    return Q_TRAN(&state_machine_state_1);
}

/*${AOs::state_machine::SM::state_1} .......................................*/
static QState state_machine_state_1(state_machine * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::state_machine::SM::state_1} */
        case Q_ENTRY_SIG: {
            state_1();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::state_machine::SM::state_1::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&state_machine_state_2);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::state_machine::SM::state_2} .......................................*/
static QState state_machine_state_2(state_machine * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::state_machine::SM::state_2} */
        case Q_ENTRY_SIG: {
            state_2();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::state_machine::SM::state_2::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&state_machine_state_3);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::state_machine::SM::state_3} .......................................*/
static QState state_machine_state_3(state_machine * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::state_machine::SM::state_3} */
        case Q_ENTRY_SIG: {
            state_3();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::state_machine::SM::state_3::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&state_machine_state_1);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::state_machine} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

